### ISSUE TITLE
.vagrant must be gitignored

### ISSUE THREAD

**Issue by satoryu** [ngtk/napsac#2]
`.vagrant` dir stores some information depending on a platform which actually is provisioned with `vagrant`. files under the dir have information related to your machine. 

For instance, an attribute of [`synced_folders`](https://github.com/ngtk/napsac/blob/master/vagrant/.vagrant/machines/default/virtualbox/synced_folders) includes the full path of your home folder. 

if you want to publicize vagrant configuration, you should push only `Vagrantfile` and some recipes, in your case `main.yml`.

**Comment by ngtk** [comment]
Oops... :sweat_drops: thank you for your heads-up! :smile_cat: 

Once, I'm going to make this repository private until I fix it. thank you.
